=pod

=encoding utf8

=head1 NAME

Konekt

=head1 SYNOPSIS

	./konekt daemon

=head1 DESCRIPTION

A simple platform for creating rich web applications.

=head2 CPAN Setup

	cpanm Modern::Perl Mojolicious::Lite DBIx::Class::Candy DateTime::Format::ISO8601 DateTime::Format::SQLite REST::Google::Search GIS::Distance Crypt::SaltedHash

=head1 BUGS

	http://github.com/ispyhumanfly/konekt/issues

=head1 SEE ALSO

	http://github.com/ispyhumanfly/konekt/wiki

=head1 LICENSE

This is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=cut

