=pod

=encoding utf8

=head1 NAME

SocialMAP

=head1 SYNOPSIS

	./socialmap daemon_prefork --lock socialmap.lock --pid socialmap.pid --clients 100

=head1 DESCRIPTION

A pretty cool way to interact with people centered around a unique approach to common web services.

=head2 CPAN Setup

	sudo cpanp install Mojolicious::Lite DBIx::Class REST::Google::Search GIS::Distance

=head1 BUGS

	http://github.com/insurgentsoftware/socialmap/issues

=head1 SEE ALSO

	http://github.com/insurgentsoftware/socialmap/wiki

=head1 LICENSE

This is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=cut

