=pod

=encoding utf8

=head1 NAME

Moonfuzz

=head1 SYNOPSIS

	./moonfuzz daemon

=head1 DESCRIPTION

The source code for moonfuzz.com

=head2 CPAN Setup

	cpanm -l lib/ Modern::Perl Mojolicious::Lite DBIx::Class::Candy DateTime::Format::ISO8601 DateTime::Format::SQLite REST::Google::Search GIS::Distance Crypt::SaltedHash

=head1 BUGS

	http://github.com/insurgentsoftware/moonfuzz/issues

=head1 SEE ALSO

	http://github.com/insurgentsoftware/moonfuzz/wiki

=head1 LICENSE

This is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=cut

