#!/usr/bin/env perl

use Mojolicious::Lite;

get '/' => sub {

    my $self = shift;
    $self->render( 'home', layout => 'default' );

} => 'index';

# p a g e s . . .

get '/local' => sub {

    my $self = shift;
    $self->render( 'local', layout => 'default' );

} => 'local';

get '/image' => sub {

    my $self = shift;
    $self->render( 'image', layout => 'default' );

} => 'image';


# a c t i o n s . . .

get '/login' => sub {

    my $self = shift;

    if ( $self->param('name') ) {
        
        my $name = $self->param('name');

        $self->session( name => $name );
        $self->redirect_to('home');
    }
    else {

        return $self->render        
    }

} => 'login';

get '/logout' => sub {

    my $self = shift;

    $self->session( expires => 1 );
    $self->redirect_to('index');

} => 'logout';

app->secret('Insurgent Software Rocks!');
app->start;

__DATA__

@@ exception.html.ep

@@ not_found.html.ep
