=pod

=encoding utf8

=head1 NAME

SocialMAP Developer Scratch Directory

=head1 SYNOPSIS

	mkdir <project_name> && git add <project_name> && git commit -m "I added a project directory..."

=head1 DESCRIPTION

This is a working directory for all developers.  This is a place for one off
prototyping and initial work on features that will most likely be added to the
core of the product.  Please create your own directory ie. dev/ispyhumanfly or
dev/project_name to work from.


=cut
