#!/usr/bin/env perl
 
use 5.010_000;
use strict;
use warnings;

use lib 'lib';
use Model::Schema;

my $MODEL = Model::Schema->connect('dbi:SQLite:socialmap.db');

### User Table

my @users = $MODEL->resultset('User')->search(undef, { order_by => 'user_id ASC' } );

say "\nContents of table 'user'.\n";

#for my $user (@users) {
#    
#    say $user->user_id;
#    say $user->facebook_id;
#    say $user->name;
#    say $user->first_name;
#    say 
#}
### Place Table

my @places = $MODEL->resultset('Place')->search();

say "\nEntries inside table 'place'\n";

for my $place (@places) {
    
    say "\n\t$place->user_id";
    
}

#### Events
#
#my @events = $MODEL->resultset('Event')->search();
#
#say "\n Contents of table 'event'\n";
#
#for my $event (@events) {
#    
#    for ( keys %{ $place } ) {
#        
#        say "$_ \n $place->{$_}";
#    }
#}
#
#### Stories
#
#my @stories = $MODEL->resultset('Story')->search();
#
#say "\n Contents of table 'story'\n";
#
#for my $story (@stories) {
#    
#    say $story->title;
#}
#
#### Ads
#
#say "\n Contents of table 'place'\n";
#
#my @images = $MODEL->resultset('PlaceImage')->search();
#
#for my $image (@images) {
#    
#    say print $image->title;
#}
