#!/usr/bin/env perl

use strict;
use warnings;

use lib '../lib';
use Model::Schema;

my $MODEL = Model::Schema->connect('dbi:SQLite:../socialmap.db');

### List...

my @tracking = $MODEL->resultset('PersonTracking')->search();

for my $person (@tracking) {
    
    print $person->name;
}