#!/usr/bin/env perl

use Modern::Perl;

use lib 'lib/';
use Model::Schema;

my $MODEL = Model::Schema->connect('dbi:SQLite:socialmap.db');

my @people = $MODEL->resultset('Person')->all;

for (@people) {

    my @tracking;

    push @tracking, ( $_ + rand [10] ) for 0 .. 10;

    my $csv = join ',', @tracking;

    $_->tracking( $csv );
    
    $_->update;
}

say $_->tracking for @people;
